### ISSUE TITLE
Login Bug?

### ISSUE THREAD

**Issue by DarthRidar** [Aohzan/hass-tplink-easysmartswitch#5]
Hello
When I log into the Switch, the integration no longer works. It only works again after reloading the integration.

**Comment by Aohzan** [comment]
it's because the switch ui only allow one login, when you log yourself, it disconnects HA.
I don't know if I should implement a reconnect on HA side because you will not be able to browse the UI more than 20-30s

**Comment by DarthRidar** [comment]
Thanks for the info
